export enum PaymentGroupValidationErrors {
  AMOUNT_TOO_LOW = 'AMOUNT_TOO_LOW',
  COMPLETED_EXPIRED_CANCELED = 'COMPLETED_EXPIRED_CANCELED',
  MAX_PARTICIPANTS_REACHED = 'MAX_PARTICIPANTS_REACHED',
  EMAIL_ALREADY_USED = 'EMAIL_ALREADY_USED',
  NOT_FOUND = 'NOT_FOUND',
}

export enum CheckoutSessionValidationErrors {
  WRONG_STATUS = 'WRONG_STATUS',
  NOT_FOUND = 'NOT_FOUND',
  CUSTOMER_BLOCKED = 'CUSTOMER_BLOCKED',
}
