name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

concurrency:
  group: ${{ github.head_ref && github.run_id || github.ref_name }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v4
        name: Install pnpm
        id: pnpm-install
        with:
          version: 8.6.1
          run_install: false

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.10.0
          cache: 'pnpm'

      - name: Install dependencies
        run: pnpm install
      - name: Build & Generate Types
        run: pnpm run build && pnpm run type:generate
      - name: Lint
        run: pnpm run lint && pnpm run prettier:check
      - name: Run tests
        run: pnpm run test
