version: '3.8'
services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_DB: kohort
      POSTGRES_USER: kohortusr
      POSTGRES_PASSWORD: kohortpwd
    ports:
      - 5432:5432

  redis:
    image: redis:alpine
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
volumes:
  redis-data:
